# Required
version: 2

# Build environment
build:
  os: ubuntu-22.04
  tools:
    python: "mambaforge-22.9"
  apt_packages:
    - graphviz

# Use conda environment
conda:
  environment: environment.yml

# Build documentation with Sphinx
sphinx:
  configuration: docs/source/conf.py
