version: 2


build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
  apt_packages:
    - texlive-latex-base
    - texlive-latex-extra
    - dvipng


sphinx:
  configuration: docs/source/conf.py


python:
  install:
    - requirements: requirements.txt
    - requirements: requirements_dev.txt