# Required
version: 2

# Build environment
build:
  os: ubuntu-22.04
  tools:
    python: "3.12"
  apt_packages:
    - pandoc
  jobs:
    post_install:
      - pip install -e ".[develop]"

# Build documentation with MkDocs
mkdocs:
  configuration: mkdocs.yml
