# Required
version: 2

# Build environment
build:
  os: ubuntu-22.04
  tools:
    python: "3.12"
  apt_packages:
    - graphviz

# Install package with dependencies
python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - develop

# Build documentation with Sphinx
sphinx:
  configuration: docs/source/conf.py
