#!/usr/bin/env python
"""Fail if a public ``tsam`` module is missing from the mkdocs API reference.

The API reference under ``docs/api/`` is hand-maintained: each module is exposed
via a mkdocstrings ``::: tsam.<module>`` directive. ``mkdocs build --strict``
catches directives that point at a *non-existent* module, but nothing catches
the reverse — adding a module and forgetting to document it. This check closes
that gap.

A module under ``src/tsam/`` must either be referenced by a ``:::`` directive
somewhere in ``docs/`` (module- or object-level) or be listed in ``INTERNAL``
below as intentionally undocumented. Adding a new module therefore forces a
deliberate choice: document it, or mark it internal.

Run directly (``python scripts/check_api_reference.py``) or via pre-commit.
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent.parent
SRC = ROOT / "src" / "tsam"
DOCS = ROOT / "docs"

# Modules intentionally NOT in the public API reference (implementation detail,
# generated, or package marker). Keep this list small and justified.
INTERNAL: set[str] = {
    "tsam._version",  # generated by the build backend
}

_DIRECTIVE = re.compile(r"^\s*:::\s+(tsam[\w.]*)", re.MULTILINE)


def source_modules() -> set[str]:
    """Dotted names of every importable module under src/tsam (excl. packages)."""
    modules = set()
    for path in SRC.rglob("*.py"):
        if path.name == "__init__.py":
            continue
        rel = path.relative_to(SRC.parent).with_suffix("")
        modules.add(".".join(rel.parts))
    return modules


def documented_targets() -> set[str]:
    """Every ``::: tsam.*`` target referenced anywhere in the docs."""
    targets = set()
    for md in DOCS.rglob("*.md"):
        targets.update(_DIRECTIVE.findall(md.read_text(encoding="utf-8")))
    return targets


def _is_documented(module: str, targets: set[str]) -> bool:
    # Documented by a module-level directive, or by any object inside it
    # (e.g. ``::: tsam.config.ClusterConfig`` documents tsam.config).
    return module in targets or any(t.startswith(module + ".") for t in targets)


def main() -> int:
    modules = source_modules()
    targets = documented_targets()

    missing = sorted(
        m for m in modules if m not in INTERNAL and not _is_documented(m, targets)
    )
    stale = sorted(m for m in INTERNAL if m not in modules)

    if stale:
        print("WARNING: stale INTERNAL allowlist entries (module no longer exists):")
        for m in stale:
            print(f"  - {m}")

    if missing:
        print("ERROR: these tsam modules are not in the API reference (docs/api/):")
        for m in missing:
            print(f"  - {m}")
        print(
            "\nFix by either:\n"
            "  * adding a `::: <module>` directive under docs/api/, or\n"
            "  * adding the module to INTERNAL in scripts/check_api_reference.py\n"
            "    if it is intentionally undocumented."
        )
        return 1

    print(f"API reference coverage OK ({len(modules)} modules checked).")
    return 0


if __name__ == "__main__":
    sys.exit(main())
