on:
  workflow_dispatch:
  push:
    branches: ["**"]

jobs:
  extract-python-versions:
    uses: FZJ-IEK3-VSA/.github/.github/workflows/_extract_env_versions.yml@main
    with:
      library_name: python
      env_file: environment.yml

  TestPullCondaForgeDev:
    name: Test development version on ${{ matrix.runner_tag }}
    strategy:
      fail-fast: false
      matrix:
        runner_tag: ["self-hosted"]
    uses: FZJ-IEK3-VSA/.github/.github/workflows/_run_single_conda_forge_test.yml@main
    with:
      runner_tag: ${{ matrix.runner_tag }}
      requirements_file_name: environment.yml
      multiprocessing_pytest_string: "-n auto"
      multiprocessing_example_string: "-n auto"
  TestPullPyPIDev:
    name: Test PyPI development version on ${{ matrix.runner_tag }}
    needs: extract-python-versions
    strategy:
      fail-fast: false
      matrix:
        runner_tag: ["self-hosted"]
    uses: FZJ-IEK3-VSA/.github/.github/workflows/_run_single_pypi_test_uv.yml@main
    with:
      runner_tag: ${{ matrix.runner_tag }}
      python_version: ${{ needs.extract-python-versions.outputs.max_version }}
      optional_dependency_PyPI_tag: "[develop]"
      multiprocessing_pytest_string: "-n auto"

  TestNotebooks:
    name: Run example notebooks
    uses: FZJ-IEK3-VSA/.github/.github/workflows/_run_single_conda_forge_test.yml@main
    with:
      runner_tag: "self-hosted"
      requirements_file_name: environment.yml
      examples_to_execute: "docs/notebooks/quickstart.ipynb docs/notebooks/clustering_methods.ipynb docs/notebooks/optimization_input.ipynb docs/notebooks/representations.ipynb docs/notebooks/segmentation.ipynb docs/notebooks/k_maxoids.ipynb docs/notebooks/clustering_transfer.ipynb"
      multiprocessing_pytest_string: "--co -q"
      multiprocessing_example_string: "-n auto"
