on:
    workflow_dispatch:
    pull_request:
        branches: ["master"]

jobs:
    extract-versions:
        uses: FZJ-IEK3-VSA/.github/.github/workflows/_extract_env_versions_matrix.yml@main
        with:
            libraries: "scikit-learn,pandas,numpy,pyomo,networkx,tqdm,highspy"
            version_type: both
            env_file: environment.yml

    TestDependencyVersions:
        name: Test ${{ matrix.dependencies.library_name }} ${{ matrix.dependencies.version }} (${{ matrix.dependencies.version_type }})
        needs: extract-versions
        strategy:
            fail-fast: false
            matrix:
                runner_tag: ["self-hosted"]
                dependencies: ${{ fromJSON(needs.extract-versions.outputs.matrix) }}
        uses: FZJ-IEK3-VSA/.github/.github/workflows/_run_single_conda_forge_test.yml@main
        with:
            runner_tag: ${{ matrix.runner_tag }}
            requirements_file_name: environment.yml
            examples_to_execute: "docs/notebooks/quickstart.ipynb docs/notebooks/clustering_methods.ipynb docs/notebooks/optimization_input.ipynb docs/notebooks/representations.ipynb docs/notebooks/segmentation.ipynb docs/notebooks/k_maxoids.ipynb docs/notebooks/clustering_transfer.ipynb"
            library_version: ${{ matrix.dependencies.version }}
            dependency_position_env_file: ${{ matrix.dependencies.yaml_position }}
            library_name: ${{ matrix.dependencies.library_name }}
            multiprocessing_pytest_string: "-n auto"
            multiprocessing_example_string: "-n auto"
